In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

x = torch.randn((3, 4, 5), dtype=torch.float32)
x

tensor([[[ 1.2044,  1.7967, -1.2150,  1.2451,  0.1350],
         [-0.2994, -0.3727,  0.7825, -0.3566,  1.7261],
         [-0.7643,  0.3722, -0.8795,  0.3615, -0.9138],
         [ 0.7694,  1.2116, -0.0799,  0.7327,  0.4049]],

        [[ 0.9452,  1.5816, -0.1140,  0.8002, -0.7846],
         [-0.2205, -2.1651, -0.3225,  0.4212, -1.4004],
         [-2.6371, -0.8968,  1.0360, -0.6443, -0.1215],
         [-0.1604,  0.0032, -0.7857, -0.6442,  0.8506]],

        [[-0.0931, -0.2343,  1.6653, -0.7760,  0.5168],
         [ 0.1450,  1.2377,  0.8391, -0.2881, -0.5452],
         [ 0.0223, -0.9441, -0.2421,  0.2283,  0.5509],
         [-0.8421, -0.7019, -0.0198, -0.1935,  0.1056]]])

In [3]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [6]:
# Приведите его к форме 6 X 10
x.resize_(6, 10)
x.shape

torch.Size([6, 10])

In [9]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x.resize_(3, 4, 5)
x * torch.FloatTensor([1, 4, 2, 2, 1])

tensor([[[ 1.2044,  7.1869, -2.4300,  2.4903,  0.1350],
         [-0.2994, -1.4908,  1.5651, -0.7133,  1.7261],
         [-0.7643,  1.4889, -1.7590,  0.7231, -0.9138],
         [ 0.7694,  4.8463, -0.1597,  1.4655,  0.4049]],

        [[ 0.9452,  6.3265, -0.2280,  1.6005, -0.7846],
         [-0.2205, -8.6602, -0.6450,  0.8424, -1.4004],
         [-2.6371, -3.5872,  2.0720, -1.2885, -0.1215],
         [-0.1604,  0.0127, -1.5715, -1.2885,  0.8506]],

        [[-0.0931, -0.9372,  3.3307, -1.5519,  0.5168],
         [ 0.1450,  4.9508,  1.6782, -0.5763, -0.5452],
         [ 0.0223, -3.7763, -0.4841,  0.4566,  0.5509],
         [-0.8421, -2.8077, -0.0397, -0.3869,  0.1056]]])

In [10]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
x.resize_(6, 10)
torch.matmul(x, x.transpose(0,1)).size()

torch.Size([6, 6])

In [5]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.FloatTensor([1.0]), requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2.0]), requires_grad = True)

y = x**3 + z - 75*t

y.backward()

print(f'y_x={x.grad}')
print(f'y_z={z.grad}')
print(f'y_t={t.grad}')

y_x=tensor([3.])
y_z=tensor([1.])
y_t=tensor([-75.])


In [12]:
# Создайте единичный тензор размера 5x6
x = torch.ones(5,6)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [13]:
# Переведите его в формат numpy
x.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [2]:
from torch import nn 
from torch import optim

In [6]:
# возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

w1 = Variable(torch.Tensor([0.1,0.1]), requires_grad = True)
x = Variable(torch.Tensor([2,2]), requires_grad = False)
y = Variable(torch.Tensor([2,2]), requires_grad = False)

In [7]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD([w1], lr=0.01)

In [9]:
func = x**w1 - 2 * x**2 + 5

optimizer.zero_grad()
pred = func
loss = criterion(pred, y)

loss.backward()     
optimizer.step()  

print(f'loss:\t {loss.item()}')
print(f'w1:\t {w1.data}')

loss:	 15.259385108947754
w1:	 tensor([0.1588, 0.1588])
